---
title: "ADS 503 Final Project - Team 3"
author: "Cameron Moran, Brandon Rodriguez-Andrade, Jacob Moore"
format: 
    html: 
        toc: true
        toc-depth: 4
        code-fold: true
    pdf: default
    docx: default
editor: visual
---

```{r}
library(mlbench)
library(tidyverse)
library(GGally)
library(caret)
library(e1071)
library(scales)
library(AppliedPredictiveModeling)
library(gt)
library(RANN)
library(kernlab)
library(randomForest)
library(ggcorrplot)
library(pROC)
library(nnet)
SEED <- 123
RETRAIN <- TRUE
```

```{r}
# load the data from bank_fraud.csv
bank_fraud <- read.csv("bank_fraud.csv")
# check shape of df
print(dim(bank_fraud))

# check column names
print(colnames(bank_fraud))
```

```{r}
# The dataset is 1 million rows by 26 columns, with two possible target colums (is_fraud and fraud_type). is_fraud is the target variable we will use and we will drop the other
# Drop the fraud_type column
bank_fraud <- subset(bank_fraud, select = -fraud_type)

# Convert is_fraud to a factor for classification purposes
bank_fraud$is_fraud <- as.factor(bank_fraud$is_fraud)

levels(bank_fraud$is_fraud) <- c("not_fraud", "fraud")

# Keeping a copy of the of the original data for EDA purposes
bank_fraud_raw <- bank_fraud

# I moved this chunk here so that I could apply Boxcox transformation on subset data
continuous_predictors_name_list <- c("customer_age", "credit_score", "account_age_years", "account_balance",
                      "transaction_amount", "num_prev_transactions", "transaction_freq_monthly",
                      "distance_from_home_km", "time_since_last_txn_hrs")

# Preprocessing continuous predictors using BoxCox transformation, centering, and scaling
trans <- preProcess(bank_fraud[, continuous_predictors_name_list],
                    method = c("BoxCox", "center", "scale"))

# Applying the transformations to the original data
transformed <- predict(trans, bank_fraud[, continuous_predictors_name_list])
head(transformed)

# Replacing the continuous predictor column in bank_fraud with the transformed variables
bank_fraud[, continuous_predictors_name_list] <- transformed


# Since the dataset is so large, we will also select smaller subset (1%, 1%, 5%, 10%, 25%, 50%) to train our models on and compare the results
set.seed(SEED)
bank_fraud_1 <- bank_fraud[sample(nrow(bank_fraud), size = nrow(bank_fraud)*0.01), ]
bank_fraud_5 <- bank_fraud[sample(nrow(bank_fraud), size = nrow(bank_fraud)*0.05), ]
bank_fraud_10 <- bank_fraud[sample(nrow(bank_fraud), size = nrow(bank_fraud)*0.10), ]
bank_fraud_25 <- bank_fraud[sample(nrow(bank_fraud), size = nrow(bank_fraud)*0.25), ]
bank_fraud_50 <- bank_fraud[sample(nrow(bank_fraud), size = nrow(bank_fraud)*0.50), ]

# Check shape of the first subset to confirm
print(dim(bank_fraud_1))
```

```{r}
# Check for missing values
print(colSums(is.na(bank_fraud)))
```

```{r}
# Organization cell
# Place subsets into list for iteration purposes
bank_fraud_df_list <- list(bank_fraud_1, bank_fraud_5, bank_fraud_10, bank_fraud_25, bank_fraud_50, bank_fraud)

# place predictors into a list for iteration purposes
predictors_name_list <- c("hour_of_day", "is_weekend", "country",
                      "city", "merchant_category", "payment_method", "device_type",
                      "customer_age", "credit_score", "account_age_years", "account_balance",
                      "transaction_amount", "num_prev_transactions", "transaction_freq_monthly",
                      "distance_from_home_km", "time_since_last_txn_hrs", "is_international",
                      "failed_attempts", "pin_changed_recently")

# Had to add above in order to apply BoxCox transformation on subset data (This is why I commented out)
#continuous_predictors_name_list <- c("customer_age", "credit_score", "account_age_years", "account_balance",
 #                     "transaction_amount", "num_prev_transactions", "transaction_freq_monthly",
  #                    "distance_from_home_km", "time_since_last_txn_hrs")

categorical_predictors_name_list <- c("hour_of_day", "is_weekend", "country",
                      "city", "merchant_category", "payment_method", "device_type",
                      "is_international", "failed_attempts", "pin_changed_recently")

target_name <- "is_fraud"
```

```{r}
# Non-graphical EDA cell
# Check distribution of target variable
percent_fraud <- sum(bank_fraud_raw[[target_name]] == "fraud") / nrow(bank_fraud_raw)
percent_legitimate <- 1 - percent_fraud
print(paste("Percentage of fraudulent transactions:", percent_fraud))
print(paste("Percentage of legitimate transactions:", percent_legitimate))
```

```{r}
# Start with distributions of continuous predictors using the full dataset
for (predictor in continuous_predictors_name_list) {
    print(ggplot(bank_fraud_raw, aes_string(x = predictor)) + 
        geom_histogram(bins = 25, color = "black", fill = "blue") + ggtitle(paste("Distribution of", predictor)))
}
```

```{r}
# Show distributions of categorical predictors
for (predictor in categorical_predictors_name_list) {
    print(ggplot(bank_fraud_raw, aes_string(x = predictor)) + 
        geom_bar(color = "black", fill = "blue") + ggtitle(paste("Distribution of", predictor)))
}
```

```{r}
# Show distribution of target variable
ggplot(bank_fraud_raw, aes(x = is_fraud)) + geom_bar(color = "black", fill = "blue") + ggtitle("Distribution of is_fraud")
```

```{r}
# Show plots of continuous predictors vs target variable grouped by is_fraud for boxplots
for (predictor in continuous_predictors_name_list) {
    print(ggplot(bank_fraud_raw, aes_string(x = target_name, y = predictor)) + 
        geom_boxplot() + ggtitle(paste("Boxplot of", predictor, "by", target_name)))
}
```

```{r}
# Check for relationships between variables with a correlation heatmap
corr_matrix <- cor(bank_fraud_raw[, continuous_predictors_name_list])
ggcorrplot(corr_matrix, lab = TRUE, digits = 4, title = "Correlation Heatmap of Continuous Predictors")
```

```{r}
# Visually identify outliers in the continuous predictors using boxplots
for (predictor in continuous_predictors_name_list) {
    print(ggplot(bank_fraud_raw, aes_string(x = predictor)) + 
        geom_boxplot() + ggtitle(paste("Boxplot of", predictor)))
}
```

```{r}
# Basic summary statistics of continuous predictors
print(summary(bank_fraud_raw[, continuous_predictors_name_list]))
```

```{r}
# Check for degenerate predictors (predictors with only one unique value)
for (predictor in continuous_predictors_name_list) {
    if (length(unique(bank_fraud_raw[[predictor]])) == 1) {
        print(paste("Degenerate predictor:", predictor, "with unique value:", unique(bank_fraud_raw[[predictor]])))
    }
}
```

```{r}
# Check how well components of PCA can explain the variance of the data
pca_output <- prcomp(bank_fraud_raw[, continuous_predictors_name_list])
print(summary(pca_output))
```

```{r}
# Create train/test partitions for each of the subsets
set.seed(SEED)
training_set_list <- list()
test_set_list <- list()
for (subset in bank_fraud_df_list) {
    curr_train_rows <- createDataPartition(subset[[target_name]], p = 0.8, list = FALSE)
    curr_train_data <- subset[curr_train_rows, ]
    curr_test_data <- subset[-curr_train_rows, ]
    training_set_list <- append(training_set_list, list(curr_train_data))
    test_set_list <- append(test_set_list, list(curr_test_data))
}

# Now there are 2 lists (training_set_list and test_set_list) containing 7 dataframes each
# The order of subsets is 1%, 5%, 10%, 25%, 50%, and 100% of the original dataset in both lists
# So this means training_set_list[1] is the training set for the 1% subset
```

```{r}
# Baseline model training (default hyperparameters) with 1% subset and evaluation to determine models to tune
set.seed(SEED)
predictors_formula <- as.formula(paste(target_name, "~", paste(predictors_name_list, collapse = " + ")))
# - Random Forest
if (RETRAIN) {
    # train rf using predictors_name_list as predictors and is_fraud as target variable
   random_forest_1 <- randomForest(predictors_formula, data = training_set_list[[1]])
}
random_forest_1_predictions <- predict(random_forest_1, newdata = test_set_list[[1]])
print(paste0("Random Forest Test Accuracy on 1% subset: ", sum(random_forest_1_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for Random Forest on 1% subset:")
print(table(test_set_list[[1]][[target_name]], random_forest_1_predictions))

# - Logistic Regression
if (RETRAIN) {
    logistic_regression_1 <- glm(predictors_formula, data = training_set_list[[1]], family = binomial)
}
logistic_regression_1_predictions <- predict(logistic_regression_1, newdata = test_set_list[[1]])
logistic_regression_1_class_predictions <- ifelse(logistic_regression_1_predictions > 0.5, "fraud", "not_fraud")
print(paste0("Logistic Regression Test Accuracy on 1% subset: ", sum(logistic_regression_1_class_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for Logistic Regression on 1% subset:")
print(table(test_set_list[[1]][[target_name]], logistic_regression_1_class_predictions))

# # - SVM
svm_1 <- ksvm(predictors_formula, data = training_set_list[[1]], kernel = "rbfdot")
svm_1_predictions <- predict(svm_1, newdata = test_set_list[[1]])
print(paste0("SVM Test Accuracy on 1% subset: ", sum(svm_1_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for SVM on 1% subset:")
print(table(test_set_list[[1]][[target_name]], svm_1_predictions))

# # - KNN
knn_1 <- train(predictors_formula, data = training_set_list[[1]], method = "knn", tuneLength = 1)
knn_1_predictions <- predict(knn_1, newdata = test_set_list[[1]])
print(paste0("KNN Test Accuracy on 1% subset: ", sum(knn_1_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for KNN on 1% subset:")
print(table(test_set_list[[1]][[target_name]], knn_1_predictions))

# # - Neural Network
neural_network_1 <- nnet(predictors_formula, data = training_set_list[[1]], size = 1)
neural_network_1_predictions <- predict(neural_network_1, newdata = test_set_list[[1]], type = "class")
print(paste0("Neural Network Test Accuracy on 1% subset: ", sum(neural_network_1_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for Neural Network on 1% subset:")
print(table(test_set_list[[1]][[target_name]], neural_network_1_predictions))

# # - Naive Bayes
naive_bayes_1 <- naiveBayes(predictors_formula, data = training_set_list[[1]])
naive_bayes_1_predictions <- predict(naive_bayes_1, newdata = test_set_list[[1]])
print(paste0("Naive Bayes Test Accuracy on 1% subset: ", sum(naive_bayes_1_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for Naive Bayes on 1% subset:")
print(table(test_set_list[[1]][[target_name]], naive_bayes_1_predictions))

# - Linear Discriminant Analysis
lda_1 <- lda(predictors_formula, data = training_set_list[[1]])
lda_1_predictions <- predict(lda_1, newdata = test_set_list[[1]])
lda_1_class_predictions <- lda_1_predictions$class
print(paste0("LDA Test Accuracy on 1% subset: ", sum(lda_1_class_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for LDA on 1% subset:")
print(table(test_set_list[[1]][[target_name]], lda_1_class_predictions))

# - Penalized Logistic Regression
penalized_logistic_regression_1 <- train(predictors_formula, data = training_set_list[[1]], method = "glmnet", family = "binomial", tuneLength = 1)
penalized_logistic_regression_1_predictions <- predict(penalized_logistic_regression_1, newdata = test_set_list[[1]])
print(paste0("Penalized Logistic Regression Test Accuracy on 1% subset: ", sum(penalized_logistic_regression_1_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for Penalized Logistic Regression on 1% subset:")
print(table(test_set_list[[1]][[target_name]], penalized_logistic_regression_1_predictions))

# - Nearest Shrunken Centroids
nearest_shrunken_centroids_1 <- train(predictors_formula, data = training_set_list[[1]], method = "pam", tuneLength = 1)
nearest_shrunken_centroids_1_predictions <- predict(nearest_shrunken_centroids_1, newdata = test_set_list[[1]])
print(paste0("Nearest Shrunken Centroids Test Accuracy on 1% subset: ", sum(nearest_shrunken_centroids_1_predictions == test_set_list[[1]][[target_name]]) / nrow(test_set_list[[1]])))
print("Confusion Matrix for Nearest Shrunken Centroids on 1% subset:")
print(table(test_set_list[[1]][[target_name]], nearest_shrunken_centroids_1_predictions))
```

**The models seem to be predicting the majority class (not fraud) for almost all rows. This means the models achieve \~94.5% accuracy, but this is only because the dataset is imbalance with around 5.5% of all observations being fraud. These models are not ideal for a final model. They just serve a decent baseline to understanding how models are likely to perform with no tuning.**

```{r}
set.seed(SEED)
ctrl <- trainControl(method = "cv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

lr_models <- list()
testResults_list <- list()
subset_labels <- c("1%", "5%", "10%")

for (i in 1:3) {
    print(paste0("Logistic Regression — ", subset_labels[i], " subset"))

    trainData <- training_set_list[[i]]
    testData <- test_set_list[[i]]
    predictor_cols <- predictors_name_list

    lrFit <- train(x = trainData[, predictor_cols],
                   y = trainData$is_fraud,
                   method = "glm",
                   metric = "ROC",
                   trControl = ctrl)
    print(lrFit)
    lr_models[[i]] <- lrFit

    # Confusion matrix from cross-validated predictions
    lrCM <- confusionMatrix(lrFit, norm = "none")
    print(lrCM)

    # ROC curve from cross-validated predictions
    lrRoc <- roc(response = lrFit$pred$obs,
                predictor = lrFit$pred$fraud,
                levels = rev(levels(lrFit$pred$obs)))
    plot(lrRoc, legacy.axes = TRUE, main = paste("Logistic Regression ROC -", subset_labels[i]))
    print(paste0("AUC for the ", subset_labels[i], " subset: ", round(lrRoc$auc, 3)))

    # Variable importance
    lrImp <- varImp(lrFit, scale = FALSE)
    plot(lrImp)

    # Saving test-set predictions for the later model comparison step
    testResults_list[[i]] <- data.frame(obs = testData$is_fraud,
                                         LR = predict(lrFit, testData[, predictor_cols]))
}
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
